apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress-https
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`tylerpitcher.com`, `www.tylerpitcher.com`) && PathPrefix(`/argocd`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
  tls:
    secretName: tls-secret
